---
name: "Release Changelog"
description: "A reusable action to automatically update a changelog based on GitHub releases."
author: "LizardByte"

branding:
  icon: list
  color: green

inputs:
  changelogBranch:
    description: 'The branch to store the changelog in.'
    required: false
    default: 'changelog'
  changelogFile:
    description: 'The file to store the changelog in.'
    required: false
    default: 'CHANGELOG.md'
  token:
    description: 'Github Token.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Changelog
      env:
        changelog_branch: ${{ inputs.changelogBranch }}
        changelog_file: ${{ inputs.changelogFile }}
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.token }}
        script: |
          const generateReleaseChangelog = require('${{ github.action_path }}/changelog.js');
          await generateReleaseChangelog({ github, context, core });
