---
name: "Release Homebrew"
description: "A reusable action to audit, install, test, and publish a Homebrew formula."
author: "LizardByte"

branding:
  icon: package
  color: green

inputs:
  contribute_to_homebrew_core:
    description: 'Whether to contribute to homebrew-core.'
    default: 'false'
    required: false
  formula_file:
    description: 'The full path to the formula file.'
    required: true
  git_email:
    description: 'The email to use for the commit.'
    required: true
  git_username:
    description: 'The username to use for the commit.'
    required: true
  homebrew_core_fork_repo:
    description: 'The forked homebrew-core repository to publish to.'
    default: 'LizardByte/homebrew-core'
    required: false
  homebrew_core_base_branch:
    description: 'The base branch of the homebrew-core fork to create PR against.'
    default: 'main'
    required: false
  homebrew_core_head_branch:
    description: >-
      The head branch of the homebrew-core fork to create for the PR.
      If empty, a branch name will be auto-generated.
    default: ''
    required: false
  org_homebrew_repo:
    description: |
      The target repository to publish to.
      The repo name should conform to the documentation.
      See: https://docs.brew.sh/Taps#repository-naming-conventions-and-assumptions
    default: 'LizardByte/homebrew-homebrew'
    required: false
  org_homebrew_repo_base_branch:
    description: 'The base branch of the target repository to create PR against.'
    default: ''
    required: false
  org_homebrew_repo_head_branch:
    description: >-
      The head branch of the target repository to create for the PR.
      If empty, a branch name will be auto-generated.
    default: ''
    required: false
  publish:
    description: 'Whether to publish the release.'
    default: 'false'
    required: false
  remove_labels:
    description: 'A comma-separated list of labels to remove from the PR in the org homebrew repo.'
    default: 'bottle-published,pr-pull'
    required: false
  skip_stable_version_audit:
    description: 'Whether to skip stable version audit for brew test-bot'
    default: 'true'
  token:
    description: 'Github Token. This is required when `publish` is enabled.'
    required: false
  upstream_homebrew_core_repo:
    description: 'The upstream homebrew-core repository that the fork is based on. Must be a GitHub repo.'
    default: 'Homebrew/homebrew-core'
    required: false
  validate:
    description: 'Whether to validate the formula.'
    default: 'true'
    required: false
  brew-gh-api-token:
    description: 'Token to be used for GitHub API operations within brew. This is required to allow access to the GitHub API when running from forks.'
    default: ''
    required: false

outputs:
  buildpath:
    description: "The path to Homebrew's temporary build directory."
    value: ${{ steps.homebrew-tests.outputs.buildpath }}
  testpath:
    description: "The path to Homebrew's temporary test directory."
    value: ${{ steps.homebrew-tests.outputs.testpath }}
  commit_message:
    description: "The commit message used for the formula update."
    value: ${{ steps.homebrew-tests.outputs.commit_message }}

runs:
  using: "composite"
  steps:
    - name: OS check
      id: os-check
      shell: bash
      run: |
        echo "Detected OS: ${{ runner.os }}"
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          # fail if Windows
          echo "${{ runner.os }} is not supported" >&2
          exit 1
        fi

    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        update-environment: false

    - name: Create venv
      id: venv
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "::group::Create venv"
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          # use cygpath to convert windows path to unix path while creating venv
          $(cygpath.exe -u "${{ steps.setup-python.outputs.python-path }}") -m venv venv

          # set python executable as step output
          echo "python-path=$(cygpath.exe -u $(pwd)\\venv\\Scripts\\python.exe)" >> $GITHUB_OUTPUT
        else
          ${{ steps.setup-python.outputs.python-path }} -m venv venv

          # set python executable as step output
          echo "python-path=$(pwd)/venv/bin/python" >> $GITHUB_OUTPUT
        fi
        echo "::endgroup::"

    - name: Install Python Requirements
      id: install-requirements
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "::group::Install Python Requirements"
        # install requirements required for this action to complete
        "${{ steps.venv.outputs.python-path }}" -m pip install -r requirements.txt
        echo "::endgroup::"

    - name: Checkout (org homebrew repo)
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.org_homebrew_repo }}
        ref: ${{ inputs.org_homebrew_repo_base_branch }}
        path: ${{ github.workspace }}/release_homebrew_action/org_homebrew_repo
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of the personal token
        fetch-depth: 1

    - name: Checkout (homebrew-core)
      if: ${{ inputs.contribute_to_homebrew_core == 'true' }}
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.homebrew_core_fork_repo }}
        ref: ${{ inputs.homebrew_core_base_branch }}
        path: ${{ github.workspace }}/release_homebrew_action/homebrew_core_fork_repo
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of the personal token
        fetch-depth: 1

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main
      with:
        brew-gh-api-token: ${{ inputs.brew-gh-api-token || github.token }}
        stable: true

    - name: Homebrew tests
      env:
        INPUT_FORMULA_FILE: ${{ inputs.formula_file }}
        INPUT_CONTRIBUTE_TO_HOMEBREW_CORE: ${{ inputs.contribute_to_homebrew_core }}
        INPUT_GIT_EMAIL: ${{ inputs.git_email }}
        INPUT_GIT_USERNAME: ${{ inputs.git_username }}
        INPUT_ORG_HOMEBREW_REPO: ${{ inputs.org_homebrew_repo }}
        INPUT_ORG_HOMEBREW_REPO_HEAD_BRANCH: ${{ inputs.org_homebrew_repo_head_branch }}
        INPUT_HOMEBREW_CORE_HEAD_BRANCH: ${{ inputs.homebrew_core_head_branch }}
        INPUT_SKIP_STABLE_VERSION_AUDIT: ${{ inputs.skip_stable_version_audit }}
        INPUT_UPSTREAM_HOMEBREW_CORE_REPO: ${{ inputs.upstream_homebrew_core_repo }}
        INPUT_VALIDATE: ${{ inputs.validate }}
      id: homebrew-tests
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        "${{ steps.venv.outputs.python-path }}" -u main.py

    - name: GitHub Push (org homebrew repo)
      if: ${{ inputs.publish == 'true' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
        ORG_HOMEBREW_REPO_BRANCH: ${{ steps.homebrew-tests.outputs.org_homebrew_repo_branch }}
        INPUT_ORG_HOMEBREW_REPO: ${{ inputs.org_homebrew_repo }}
      shell: bash
      working-directory: ${{ github.workspace }}/release_homebrew_action/org_homebrew_repo
      run: |
        # Push the branch to remote
        git push https://x-access-token:${GH_TOKEN}@github.com/${INPUT_ORG_HOMEBREW_REPO}.git \
          ${ORG_HOMEBREW_REPO_BRANCH}:${ORG_HOMEBREW_REPO_BRANCH} \
          --force

    - name: GitHub Push (homebrew-core)
      if: ${{ inputs.contribute_to_homebrew_core == 'true' && inputs.publish == 'true' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
        HOMEBREW_CORE_BRANCH: ${{ steps.homebrew-tests.outputs.homebrew_core_branch }}
        HOMEBREW_CORE_FORK_REPO: ${{ inputs.homebrew_core_fork_repo }}
      shell: bash
      working-directory: ${{ github.workspace }}/release_homebrew_action/homebrew_core_fork_repo
      run: |
        # Push the branch to remote
        git push https://x-access-token:${GH_TOKEN}@github.com/${HOMEBREW_CORE_FORK_REPO}.git \
          ${HOMEBREW_CORE_BRANCH}:${HOMEBREW_CORE_BRANCH} \
          --force

    - name: Create Pull Request (org homebrew repo)
      env:
        COMMIT_MESSAGE: ${{ steps.homebrew-tests.outputs.commit_message }}
        GH_TOKEN: ${{ inputs.token }}
        ORG_HOMEBREW_REPO_BRANCH: ${{ steps.homebrew-tests.outputs.org_homebrew_repo_branch }}
        ORG_HOMEBREW_REPO_BASE_BRANCH: ${{ inputs.org_homebrew_repo_base_branch }}
        INPUT_ORG_HOMEBREW_REPO: ${{ inputs.org_homebrew_repo }}
        INPUT_REMOVE_LABELS: ${{ inputs.remove_labels }}
      if: ${{ inputs.publish == 'true' }}
      shell: bash
      working-directory: ${{ github.workspace }}/release_homebrew_action/org_homebrew_repo
      run: |
        # Use default branch 'master' if base branch is not specified
        BASE_BRANCH=${ORG_HOMEBREW_REPO_BASE_BRANCH:-master}

        # Check if a pull request already exists with the same head branch
        PR_EXISTS=$(gh pr list \
          --head "${ORG_HOMEBREW_REPO_BRANCH}" \
          --repo "${INPUT_ORG_HOMEBREW_REPO}")

        # If the pull request does not exist, create it
        if [[ -z "$PR_EXISTS" ]]; then
          echo "Creating pull request"

          # https://cli.github.com/manual/gh_pr_create
          gh pr create \
            --base "${BASE_BRANCH}" \
            --head "${ORG_HOMEBREW_REPO_BRANCH}" \
            --title "chore: ${COMMIT_MESSAGE}" \
            --body \
              "Created by the LizardByte [release_homebrew](https://github.com/LizardByte/actions) action" \
            --repo "${INPUT_ORG_HOMEBREW_REPO}"
        else
          echo "Editing pull request"

          PR_NUMBER=$(echo "${PR_EXISTS}" | grep -oE '^[0-9]+')

          # https://cli.github.com/manual/gh_pr_edit
          gh pr edit "${PR_NUMBER}" \
            --title "chore: ${COMMIT_MESSAGE}" \
            --remove-label "${INPUT_REMOVE_LABELS}" \
            --repo "${INPUT_ORG_HOMEBREW_REPO}"
        fi

    - name: Create Pull Request (homebrew-core)
      env:
        COMMIT_MESSAGE: ${{ steps.homebrew-tests.outputs.commit_message }}
        GH_TOKEN: ${{ inputs.token }}
        HOMEBREW_CORE_BRANCH: ${{ steps.homebrew-tests.outputs.homebrew_core_branch }}
        HOMEBREW_CORE_BASE_BRANCH: ${{ inputs.homebrew_core_base_branch }}
        HOMEBREW_CORE_FORK_REPO: ${{ inputs.homebrew_core_fork_repo }}
        INPUT_UPSTREAM_HOMEBREW_CORE_REPO: ${{ inputs.upstream_homebrew_core_repo }}
      if: ${{ inputs.contribute_to_homebrew_core == 'true' && inputs.publish == 'true' }}
      shell: bash
      working-directory: ${{ github.workspace }}/release_homebrew_action/homebrew_core_fork_repo
      run: |
        # Use default branch 'main' if base branch is not specified
        BASE_BRANCH=${HOMEBREW_CORE_BASE_BRANCH:-main}

        # Extract fork owner from fork repo (e.g., "owner/homebrew-core" -> "owner")
        FORK_OWNER=$(echo ${HOMEBREW_CORE_FORK_REPO} | cut -d'/' -f1)

        # Check if a pull request already exists from fork to upstream
        # We check in the upstream repo for PRs from our fork
        PR_EXISTS=$(gh pr list \
          --head "${FORK_OWNER}:${HOMEBREW_CORE_BRANCH}" \
          --repo "${INPUT_UPSTREAM_HOMEBREW_CORE_REPO}")

        # If the pull request does not exist, create it
        if [[ -z "$PR_EXISTS" ]]; then
          echo "Creating pull request from ${HOMEBREW_CORE_FORK_REPO} to ${INPUT_UPSTREAM_HOMEBREW_CORE_REPO}"

          # Create PR in the upstream repo, from our fork
          # Note: we're in the fork's working directory, so gh will use the fork's context
          # https://cli.github.com/manual/gh_pr_create
          gh pr create \
            --repo "${INPUT_UPSTREAM_HOMEBREW_CORE_REPO}" \
            --base "${BASE_BRANCH}" \
            --head "${FORK_OWNER}:${HOMEBREW_CORE_BRANCH}" \
            --title "${COMMIT_MESSAGE}" \
            --body "Created by the LizardByte [release_homebrew](https://github.com/LizardByte/actions) action"
        else
          echo "Pull request already exists"
        fi
