---
name: "More space"
description: "A reusable action to free up GitHub hosted runner space."
author: "LizardByte"

branding:
  icon: hard-drive
  color: green

inputs:
  analyze-space-savings:
    description: "Generate detailed analysis of space savings by each input option"
    required: false
    default: "false"
  clean-all:
    description: "When true, all inputs except 'safe_packages' are ignored"
    required: false
    default: "false"
  remove-android:
    description: "Remove Android SDK"
    required: false
    default: "false"
  remove-chocolatey:
    description: "Remove Chocolatey (Windows only)"
    required: false
    default: "false"
  remove-codeql:
    description: "Remove CodeQL databases"
    required: false
    default: "false"
  remove-docker-images:
    description: "Remove Docker images"
    required: false
    default: "false"
  remove-docs-linux:
    description: "Remove /usr/share/doc (Linux only)"
    required: false
    default: "false"
  remove-dotnet:
    description: "Remove .NET runtime and tools"
    required: false
    default: "false"
  remove-haskell:
    description: "Remove Haskell"
    required: false
    default: "false"
  remove-homebrew:
    description: "Remove Homebrew (Linux/macOS only)"
    required: false
    default: "false"
  remove-jvm:
    description: "Remove JVMs"
    required: false
    default: "false"
  remove-swift:
    description: "Remove Swift (Linux/macOS only)"
    required: false
    default: "false"
  remove-tool-cache:
    description: "Remove runner tool cache"
    required: false
    default: "false"
  remove-tools-windows:
    description: "Remove /c/tools (Windows only)"
    required: false
    default: "false"
  remove-xcode:
    description: "Remove Xcode (macOS only)"
    required: false
    default: "false"
  safe-packages:
    description: "A list of packages to keep. The action will try to find the location of these and preserve them."
    required: false
    default: ""
  space-target:
    description: "Target amount of disk space to free in GB. The action will stop once this amount is reached."
    required: false
    default: ""

outputs:
  space-after:
    description: "Free disk space after cleanup (GB)"
    value: ${{ steps.cleanup.outputs.space-after }}
  space-analysis:
    description: "JSON formatted analysis of space savings by input option (sorted by space saved)"
    value: ${{ steps.cleanup.outputs.space-analysis }}
  space-before:
    description: "Free disk space before cleanup (GB)"
    value: ${{ steps.cleanup.outputs.space-before }}
  space-saved:
    description: "Amount of disk space saved (GB)"
    value: ${{ steps.cleanup.outputs.space-saved }}

runs:
  using: "composite"
  steps:
    - run: which jq
      shell: bash

    - name: Make cleanup script executable
      shell: bash
      run: chmod +x "${{ github.action_path }}/cleanup.sh"

    - name: Free up disk space
      env:
        INPUT_ANALYZE_SPACE_SAVINGS: ${{ inputs.analyze-space-savings }}
        INPUT_CLEAN_ALL: ${{ inputs.clean-all }}
        INPUT_REMOVE_ANDROID: ${{ inputs.remove-android }}
        INPUT_REMOVE_CHOCOLATEY: ${{ inputs.remove-chocolatey }}
        INPUT_REMOVE_CODEQL: ${{ inputs.remove-codeql }}
        INPUT_REMOVE_DOCKER_IMAGES: ${{ inputs.remove-docker-images }}
        INPUT_REMOVE_DOCS_LINUX: ${{ inputs.remove-docs-linux }}
        INPUT_REMOVE_DOTNET: ${{ inputs.remove-dotnet }}
        INPUT_REMOVE_HASKELL: ${{ inputs.remove-haskell }}
        INPUT_REMOVE_HOMEBREW: ${{ inputs.remove-homebrew }}
        INPUT_REMOVE_JVM: ${{ inputs.remove-jvm }}
        INPUT_REMOVE_SWIFT: ${{ inputs.remove-swift }}
        INPUT_REMOVE_TOOL_CACHE: ${{ inputs.remove-tool-cache }}
        INPUT_REMOVE_TOOLS_WINDOWS: ${{ inputs.remove-tools-windows }}
        INPUT_REMOVE_XCODE: ${{ inputs.remove-xcode }}
        INPUT_SAFE_PACKAGES: ${{ inputs.safe-packages }}
        INPUT_SPACE_TARGET: ${{ inputs.space-target }}
      id: cleanup
      shell: bash
      run: |
        "${{ github.action_path }}/cleanup.sh" \
          --analyze-space-savings="${INPUT_ANALYZE_SPACE_SAVINGS}" \
          --clean-all="${INPUT_CLEAN_ALL}" \
          --remove-android="${INPUT_REMOVE_ANDROID}" \
          --remove-chocolatey="${INPUT_REMOVE_CHOCOLATEY}" \
          --remove-codeql="${INPUT_REMOVE_CODEQL}" \
          --remove-docker-images="${INPUT_REMOVE_DOCKER_IMAGES}" \
          --remove-docs-linux="${INPUT_REMOVE_DOCS_LINUX}" \
          --remove-dotnet="${INPUT_REMOVE_DOTNET}" \
          --remove-haskell="${INPUT_REMOVE_HASKELL}" \
          --remove-homebrew="${INPUT_REMOVE_HOMEBREW}" \
          --remove-jvm="${INPUT_REMOVE_JVM}" \
          --remove-swift="${INPUT_REMOVE_SWIFT}" \
          --remove-tool-cache="${INPUT_REMOVE_TOOL_CACHE}" \
          --remove-tools-windows="${INPUT_REMOVE_TOOLS_WINDOWS}" \
          --remove-xcode="${INPUT_REMOVE_XCODE}" \
          --safe-packages="${INPUT_SAFE_PACKAGES}" \
          --space-target="${INPUT_SPACE_TARGET}"
