---
name: "Facebook Post"
description: "GitHub Action for posting to a Facebook page or group."
author: "LizardByte"

branding:
  icon: facebook
  color: green

inputs:
  page_id:
    description: "The page/group id to post to."
    required: false
  access_token:
    description: "The permanent Facebook access token."
    required: false
  message:
    description: "The message content of the post."
    required: true
  url:
    description: "The url to include with the post."
    required: false
  fail_on_error:
    description: "Set to False to allow the workflow to succeed for groups that don't have the app installed."
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
