---
name: "Pinact"
description: "Run pinact against repositories in an organization and create PRs for updates."
author: "LizardByte"

branding:
  icon: arrow-up-circle
  color: green

inputs:
  dryRun:
    description: 'Dry run mode. If true, will not push changes or create pull requests.'
    required: false
    default: 'false'
  gitAuthorEmail:
    description: 'Git commit author email.'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  gitAuthorName:
    description: 'Git commit author name.'
    required: false
    default: 'github-actions[bot]'
  githubOrg:
    description: |
      GitHub organization or user to process repositories from.
      Defaults to the current repository owner.
      Ignored if repo is specified.
    required: false
    default: ''
  includeForks:
    description: 'Include forked repositories when processing an organization. Has no effect when repo is specified.'
    required: false
    default: 'false'
  pinactConfig:
    description: 'Pinact configuration file content (YAML).'
    required: false
    default: ''
  pinactRepo:
    description: 'Repository to use for pinact. Allows using a fork. Format: owner/repo.'
    required: false
    default: 'suzuki-shunsuke/pinact'
  pinactVersion:
    description: 'Version of pinact to use.'
    required: false
    default: 'latest'
  prBranchName:
    description: 'Name of the branch to create for the pull request.'
    required: false
    default: 'pinact-updates'
  repo:
    description: |
      Specific repository to run pinact on (format: owner/repo).
      If specified, runs only on this repo instead of all org repos.
    required: false
    default: ''
  token:
    description: 'GitHub Token with permissions to read repositories and create pull requests.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5  # v6.2.0
      with:
        go-version: 'stable'

    - name: Run pinact on repositories
      env:
        INPUT_DRY_RUN: ${{ inputs.dryRun }}
        INPUT_GIT_AUTHOR_EMAIL: ${{ inputs.gitAuthorEmail }}
        INPUT_GIT_AUTHOR_NAME: ${{ inputs.gitAuthorName }}
        INPUT_GITHUB_ORG: ${{ inputs.githubOrg }}
        INPUT_INCLUDE_FORKS: ${{ inputs.includeForks }}
        INPUT_PINACT_CONFIG: ${{ inputs.pinactConfig }}
        INPUT_PINACT_REPO: ${{ inputs.pinactRepo }}
        INPUT_PINACT_VERSION: ${{ inputs.pinactVersion }}
        INPUT_PR_BRANCH_NAME: ${{ inputs.prBranchName }}
        INPUT_REPO: ${{ inputs.repo }}
        PINACT_GITHUB_TOKEN: ${{ inputs.token }}
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd  # v8.0.0
      with:
        github-token: ${{ inputs.token }}
        script: |
          const script = require('${{ github.action_path }}/pinact.js');
          await script({ github, context, core });
