---
name: "Create Release"
description: "A reusable action to create a GitHub release."
author: "LizardByte"

branding:
  icon: tag
  color: green

inputs:
  allowUpdates:
    description: 'An optional flag which indicates if we should update a release if it already exists.'
    required: false
    default: 'true'
  artifactErrorsFailBuild:
    description: 'An optional flag which indicates if we should fail the build if there are errors with the artifacts.'
    required: false
    default: 'false'
  artifacts:
    description: 'The artifacts to upload.'
    required: false
    default: '*artifacts/*'
  body:
    description: 'The body of the release.'
    required: false
    default: ''
  deleteOtherPreReleases:
    description: 'Whether to delete other pre-releases.'
    required: false
    default: 'true'
  deletePreReleaseTags:
    description: 'Whether to delete other pre-releases tags.'
    required: false
    default: 'true'
  draft:
    description: 'Whether the release is a draft.'
    required: false
    default: 'false'
  generateReleaseNotes:
    description: 'Indicates if release notes should be automatically generated.'
    required: false
    default: 'true'
  keepPreReleaseCount:
    description: 'The number of pre-releases to keep. The default is 2 incase there are in process downloads.'
    required: false
    default: '2'
  name:
    description: 'The version to create.'
    required: true
  prerelease:
    description: 'Whether the release is a prerelease.'
    required: false
    default: 'true'
  sleepDuration:
    description: 'The duration to sleep in seconds before deleting tags.'
    required: false
    default: '15'
  tag:
    description: 'The tag to create.'
    required: true
  token:
    description: 'Github Token.'
    required: true
  virustotal_api_key:
    description: 'The VirusTotal API key to use for scanning the artifacts.'
    required: false

runs:
  using: "composite"
  steps:
    - name: VirusTotal
      if: inputs.virustotal_api_key != ''
      id: vt
      uses: cssnr/virustotal-action@v1.7.0
      with:
        file_globs: ${{ inputs.artifacts }}
        sha256: true
        summary: true
        update_release: false
        vt_api_key: ${{ inputs.virustotal_api_key }}

    - name: Format VirusTotal Results
      env:
        INPUT_BODY: ${{ inputs.body }}
        INPUT_TAG: ${{ inputs.tag }}
      if: inputs.virustotal_api_key != ''
      id: format-vt
      shell: bash
      run: |
        # Create body file with original content
        rb_file=release_body.md
        cat > ${rb_file} << BODY_EOF
        ${INPUT_BODY}
        BODY_EOF

        ASSETS_HEADER="ðŸ“¦ **Assets:**"

        # If we have existing results, append them
        if [ -n '${{ steps.vt.outputs.json }}' ]; then
          # Check if Assets header already exists, if not add it
          if ! grep -qF "$ASSETS_HEADER" ${rb_file}; then
            # Add separator if body exists and isn't empty
            if [ -s ${rb_file} ] && [ "$(cat ${rb_file} | tr -d '[:space:]')" != "" ]; then
              echo "" >> ${rb_file}
            fi

            {
              echo "---"
              echo "$ASSETS_HEADER"
              echo ""
              echo "| â¬‡ï¸ Download | #ï¸âƒ£ Download Count | ðŸ›¡ï¸ VirusTotal |"
              echo "|-------------|-------------------|---------------|"
            } >> ${rb_file}
          fi

          # Append VirusTotal results as table rows
          printf '%s\n' '${{ steps.vt.outputs.json }}' | \
            jq -r \
              --arg repo "${{ github.repository }}" \
              --arg tag "${INPUT_TAG}" \
              '.[] |
              "| [\(.name)](https://github.com/\($repo)/releases/download/\($tag)/\(.name)) | " +
              "![Downloads](https://img.shields.io/github/downloads/\($repo)/\($tag)/\(.name)" +
                "?style=flat-square&label=&displayAssetName=false) | " +
              "[![VirusTotal](https://badges.cssnr.com/vt/id/sha256:\(.sha256)" +
                "?style=flat-square&icon=virustotal&label=)](\(.link)) |"' \
            >> ${rb_file}
        fi

        # Set output
        {
          echo "body<<EOF"
          cat ${rb_file}
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Create/Update GitHub Release
      uses: ncipollo/release-action@v1.16.0
      with:
        allowUpdates: ${{ inputs.allowUpdates }}
        artifactErrorsFailBuild: ${{ inputs.artifactErrorsFailBuild }}
        artifacts: ${{ inputs.artifacts }}
        body: ${{ steps.format-vt.outputs.body || inputs.body }}
        commit: ${{ github.sha }}
        draft: ${{ inputs.draft }}
        generateReleaseNotes: ${{ inputs.generateReleaseNotes }}
        name: ${{ inputs.name }}
        prerelease: ${{ inputs.prerelease }}
        tag: ${{ inputs.tag }}
        token: ${{ inputs.token }}

    - name: Sleep
      # wait for the new release to be available in the API
      if: inputs.deleteOtherPreReleases == 'true'
      shell: bash
      run: sleep 30

    - name: Delete Other PreReleases
      env:
        DELETE_TAGS: ${{ inputs.deletePreReleaseTags }}
        IS_DRAFT: ${{ inputs.draft }}
        KEEP_LATEST: ${{ inputs.keepPreReleaseCount }}
        SLEEP_DURATION: ${{ inputs.sleepDuration }}
        CURRENT_TAG: ${{ inputs.tag }}
      if: inputs.deleteOtherPreReleases == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          // process input
          const DELETE_TAGS = process.env.DELETE_TAGS.toLowerCase() === 'true';
          const IS_DRAFT = process.env.IS_DRAFT.toLowerCase() === 'true';
          const KEEP_LATEST = parseInt(process.env.KEEP_LATEST, 10);
          const SLEEP_DURATION = parseInt(process.env.SLEEP_DURATION, 10);
          const CURRENT_TAG = process.env.CURRENT_TAG;

          console.log(`DELETE_TAGS: ${DELETE_TAGS}`);
          console.log(`IS_DRAFT: ${IS_DRAFT}`);
          console.log(`KEEP_LATEST: ${KEEP_LATEST}`);
          console.log(`CURRENT_TAG: ${CURRENT_TAG}`);

          let regexPattern = new RegExp('^v(\\d{4,})\\.(\\d{1,4})\\.(\\d{1,6})(\\.(\\d{1,2}))?');

          // list releases
          const repoOpts = github.rest.repos.listReleases.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
          });
          const allReleases = await github.paginate(repoOpts);

          allReleases.forEach(release => {
            console.log(`Release: ${release.tag_name}`);
            console.log(`Is pre-release: ${release.prerelease}`);
            console.log(`Is draft: ${release.draft}`);
            console.log(`Matches regex: ${regexPattern.test(release.tag_name)}`);
          });

          let releasesToDelete = [];

          if (IS_DRAFT) {
            // When creating a draft, delete all other draft releases
            releasesToDelete = allReleases.filter(release =>
              release.draft &&
              regexPattern.test(release.tag_name) &&
              release.tag_name !== CURRENT_TAG
            );
            console.log('Matched Draft releases:', releasesToDelete.map(release => release.tag_name));

            // For drafts, we delete all others (don't keep any)
            // No need to sort since we're deleting all
          } else {
            // When creating a non-draft pre-release, delete all except the latest N pre-releases
            releasesToDelete = allReleases.filter(release =>
              release.prerelease &&
              regexPattern.test(release.tag_name) &&
              release.tag_name !== CURRENT_TAG
            );
            console.log('Matched Pre-release tags:', releasesToDelete.map(release => release.tag_name));

            // sort by tag/version number (e.g. v1.2.3 or v1.2.3.4)
            releasesToDelete.sort((a, b) => {
              const aParts = a.tag_name.match(/\d+/g).map(Number);
              const bParts = b.tag_name.match(/\d+/g).map(Number);
              for (let i = 0; i < Math.max(aParts.length, bParts.length); i++) {
                if (aParts[i] === undefined) return -1;
                if (bParts[i] === undefined) return 1;
                if (aParts[i] < bParts[i]) return -1;
                if (aParts[i] > bParts[i]) return 1;
              }
              return 0;
            });

            // Output sorted pre-releases
            console.log('Sorted Pre-release tags:', releasesToDelete.map(release => release.tag_name));

            // Keep only the releases to delete (remove the latest N from the list)
            releasesToDelete = releasesToDelete.slice(0, -KEEP_LATEST);
          }

          console.log('Releases to delete:', releasesToDelete.map(release => release.tag_name));

          // delete the releases
          for (const release of releasesToDelete) {
            console.log(`Deleting release: ${release.tag_name}`);
            try {
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id
              });
            } catch (error) {
              console.error(`Failed to delete release: ${release.tag_name}`);
              console.error(error);
            }
          }

          // sleep to allow any on release deleted event workflow runs to be created
          // if the tag is deleted before the workflow run is created, the run will fail to be created
          await new Promise(resolve => setTimeout(resolve, SLEEP_DURATION * 1000));

          if (DELETE_TAGS) {
            for (const release of releasesToDelete) {
              console.log(`Deleting tag: ${release.tag_name}`);
              try {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${release.tag_name}`
                });
              } catch (error) {
                console.error(`Failed to delete tag: ${release.tag_name}`);
                console.error(error);
              }
            }
          }
